import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
dotenv.config();
import { rootRouter } from './routes/index.js';
const app = express();
app.use(express.json());
app.use(cors());
app.use('/api/v1' , rootRouter);
app.listen(process.env.PORT || 3000 );